### PR TITLE
Fix scroll position restoration on history visits

### LINKED ISSUE #57: Back button scroll restoration not working
I believe that in a previous version of this plugin the scroll position was always set to the top of the screen when navigating with the back button. 

I have tried to set shouldResetScrollPosition: true on a new site I'm working on, but when navigating with the back button the scroll position is always remembered. 

I have a scroll based animation on the homepage of a site that I always need to start at the top, so ideally I would like to completely disable the scroll restoration when navigating with the back button.

Current config

const swup = new Swup({
  animateHistoryBrowsing: true,
  plugins: [
	  new SwupJsPlugin(options),
	  new SwupBodyClassPlugin(),
	  new SwupScrollPlugin({
		  animateScroll: false,
		  doScrollingRightAway: false,
		  shouldResetScrollPosition: true,
	  }),
  ],
});

Is this possible to do? Thanks in advance.

### PR DESCRIPTION
**Pull request by daun**
**Description**

- When investigating this [issue about scroll restoration](https://github.com/swup/scroll-plugin/issues/57), I've found that popstate restoration isn't working when `animateHistoryBrowsing` is enabled
- The current implementation will reset the scroll position before each visit, thus always forcing a scroll to top for all history visits as well
- The issue is solved by not resetting the position on history visits

With these changes, the following example will now correctly always scroll history visits to the top:

```js
swup.hooks.on('visit:start', (visit) => {
  if (visit.history.popstate) {
    visit.scroll.target = '#top'
  }
})
```

**Drive-by improvements**

- Apply `resolveUrl` also when caching scroll positions
- Reorder position cache/reset: cache first, then reset, to cover cases of visits to the current URL

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [ ] ~~All tests are passing (`npm run test`)~~
- [ ] ~~New or updated tests are included~~
- [ ] ~~The documentation was updated as required~~

**Additional information**

Closes #57

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -270,8 +270,8 @@ export default class SwupScrollPlugin extends Plugin {
 	 * Check whether to scroll in `visit:start` hook
 	 */
 	onVisitStart: Handler<'visit:start'> = (visit) => {
-		this.maybeResetScrollPositions(visit);
 		this.cacheScrollPositions(visit.from.url);
+		this.maybeResetScrollPositions(visit);
```
Comment (daun) [inline src/index.ts:274]: Switched these around to cache old URL first, then reset new URL, for cases where old and new URL are identical (if e.g. swup's new `linkToSelf` option is set to `navigate`)

File: src/index.ts [hunk 2]
```diff
@@ -324,12 +324,17 @@ export default class SwupScrollPlugin extends Plugin {
...
-	 * where shouldResetScrollPosition returns true for that trigger
+	 * Reset cached scroll positions. Do not reset if:
+	 * - the visit is a history visit
+	 * - the visit is triggered by a link and shouldResetScrollPosition(link) returns false
 	 */
 	maybeResetScrollPositions = (visit: Visit): void => {
+		const { popstate } = visit.history;
 		const { url } = visit.to;
 		const { el } = visit.trigger;
+		if (popstate) {
```
Comment (daun) [inline src/index.ts:335]: Don't reset scroll position before history visits. Having an `if` here also makes this potentially configurable in the fugure, e.g. `restoreHistoryScrollPosition` or so.

File: src/index.ts [hunk 3]
```diff
@@ -340,6 +345,8 @@ export default class SwupScrollPlugin extends Plugin {
 	 * Stores the scroll positions for the current URL
 	 */
 	cacheScrollPositions(url: string): void {
+		const cacheKey = this.swup.resolveUrl(url);
```
Comment (daun) [inline src/index.ts:348]: Apply `resolveUrl` here as well.

**Review by hirasso — APPROVED** [review]
